server:
  port: 8090
aws:
  cognito:
    clientId: ${CLIENT_ID}
    userPoolId: ${USER_POOL_ID}
    identityPoolId: ${IDENTITY_POOL_ID}
    region: ${REGION}
    secretKey: ${SECRET_KEY}
    accessKey: ${ACCESS_KEY}
    authFlow: ADMIN_NO_SRP_AUTH
    userNameField: cognito:username
    groupsField:
    connectionTimeout: 2000
    readTimeout: 2000
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      expense: DEBUG

    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace