spring:
  profiles:
    active: @spring.profiles.active@
info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
server:
  shutdown: graceful
fx:
  api: http://www.floatrates.com/daily/
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info