spring:
  profiles:
    active: @spring.profiles.active@
info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers